library(pomp)
library(magrittr)
set.seed(807969746L)

w <- runif(100)
k <- .Call(pomp:::systematic_resampling,w)
try(k <- .Call(pomp:::systematic_resampling,-w))

try(.Call(pomp:::probe_ccf,runif(100),runif(10),c(1,2,3),1))

pompExample(euler.sir)
euler.sir %<>% pomp(initializer=NULL)
try(simulate(euler.sir))

pompExample(gompertz)
coef(gompertz) <- coef(gompertz)[-5]
try(simulate(gompertz))

gompertz %<>% pomp(initializer=function (params, t0, ...) 5)
try(init.state(gompertz))

try(traj.match())
try(traj.match(3))
try(traj.match.objfun())
try(traj.match.objfun(3))
try(abc())
try(abc(3))
try(enkf())
try(enkf("3"))
try(eakf())
try(eakf("3"))
try(bsmc())
try(bsmc("3"))
try(bsmc2())
try(bsmc2(3L))
try(pfilter())
try(pfilter("bob"))
try(pmcmc())
try(pmcmc("bob"))
try(nlf())
try(nlf(3L))
try(mif())
try(mif(3L))
try(mif2())
try(mif2(3L))
try(probe(probes="harry"))
try(probe(33L))
try(probe.match())
try(probe.match(33L))
try(probe.match.objfun())
try(probe.match.objfun(33L))
try(spect())
try(spect(3))
try(continue())
try(continue(44))
